title: freema
description: Docs for programming, problem solving, etc.
theme: just-the-docs
url: https://mkparkqq.github.io
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# template 파일 무시
exclude:
  - '**/template'
  - '**/template.md'

# plugins
plugins:
  - jekyll-email-protect
  - jekyll-sitemap

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# code block with line numbers
compress_html:
  ignore:
    envs: all
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# 로고가 title을 가림
# logo: "/assets/logo/logo.svg"
favicon_ico: "/assets/favicon/favicon.ico"

# callouts
callouts: 
  warning:
      title: Warning
      color: red
  info:
      color: blue

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 5
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"
footer_content: "Copyright &copy written by Minkeun Park<br>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# collections
# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  minigames:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    minigames:
      # Give the collection a name
      name: Minigames
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Fold the collection in the navigation
      # Supports true or false (default)
      nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
